### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by ugintl** [cmate5614530/inventory-management#1]
Can it be installed following regular laravel installation steps? or we have to follow some special steps like in this repo https://github.com/lowildlr10/pftms

**Comment by cmate5614530** [comment]
You can install it normally.- by regular step

**Comment by ugintl** [comment]
On composer install I see following error at the end

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   InvalidArgumentException  : Please provide a valid cache path.

  at C:\laragon\www\invlara\vendor\laravel\framework\src\Illuminate\View\Compilers\Compiler.php:36
    32|      */
    33|     public function __construct(Filesystem $files, $cachePath)
    34|     {
    35|         if (! $cachePath) {
  > 36|             throw new InvalidArgumentException('Please provide a valid cache path.');
    37|         }
    38|
    39|         $this->files = $files;
    40|         $this->cachePath = $cachePath;

  Exception trace:

  1   Illuminate\View\Compilers\Compiler::__construct(Object(Illuminate\Filesystem\Filesystem))
      C:\laragon\www\invlara\vendor\laravel\framework\src\Illuminate\View\ViewServiceProvider.php:92

  2   Illuminate\View\ViewServiceProvider::Illuminate\View\{closure}(Object(Illuminate\Foundation\Application), [])
      C:\laragon\www\invlara\vendor\laravel\framework\src\Illuminate\Container\Container.php:799
```

**Comment by ugintl** [comment]
I saw this issue https://stackoverflow.com/questions/46986001/script-php-artisan-packagediscover-handling-the-post-autoload-dump-event-retur

May be it will help you

**Comment by cmate5614530** [comment]
I pushed vendor.zip. maybe it would be helpful.

**Comment by ugintl** [comment]
Thanks, but i think you should look into this issue. The stackoverflow question I shared with you has some technical answers which I do not understand. May be you will understand them. On a side note, I am using composer 2.

**Comment by ugintl** [comment]
At last, the problem is solved. create these folders under **storage/framework**:

   
- sessions
- views
- cache
- cache/data

I guess it is the `.gitignore` file. I wonder what else is `.gitignore` file keeping away. I think I should download the repo directly. **What do you suggest?** You can safely remove the vendor.zip file.

 I am logged in as admin and seeing following screen. Do I have to run `npm install` as well?

![invlara](https://user-images.githubusercontent.com/12570802/133886225-02c6fdd4-9c46-4ced-8dc1-b234b35b7e71.jpeg)

**Comment by ugintl** [comment]
@cmate5614530 I ran `npm install` and then `npm run dev` but still seeing unstyled pages. Using Nodejs 12. Also tried 14.
